### ISSUE TITLE
提个建议：对于1.1.5版本以后希望能够附带使用说明文档

### ISSUE THREAD

**Issue by CailingCailingHandcraft** [kkocdko/mobp#2]
在1.1.5版本后，程序使用了xlk扩展而不是csv。然而excel并不会默认关联.xlk格式（此时在WIN10默认应用设置里也没有该格式），需要在使用excel的备份功能之后才能关联上.xlk格式，否则程序会提示错误无法成功运行。
错误提示如下：该文件没有与之关联的应用来执行该操作。请安装应用，若已安装应用，请在“默认应用设置”页面中创建关联。

**Comment by kkocdko** [comment]
经过测试，使用 [Office Tool Plus](https://otp.landian.vip/zh-cn/) 全新安装 Office 2019 和 2021，联想笔记本预装的 Office 2019 学生版，Win11 + Office 365，均默认关联 xlk 扩展名。

在报告问题前，请先明确问题是否与事实相符。
